apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

bases:
- ../../base

namePrefix: dev-
nameSuffix: ""

commonLabels:
  environment: development

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: dev-frontend
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: gcr.io/google-samples/microservices-demo/frontend:v0.3.9
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 256Mi
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 250m

- target:
    group: autoscaling
    version: v2
    kind: HorizontalPodAutoscaler
    name: dev-frontend
  patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3
