apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

commonLabels:
  app.kubernetes.io/name: online-boutique
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  description: "Online Boutique Microservices Demo"

resources:
- frontend.yaml

replicas:
- name: frontend
  count: 3

patchesJson6902: []
patchesStrategicMerge: []
